### ISSUE TITLE
Asignar Residente Encargado

### ISSUE THREAD

**Issue by JezerMejia** [FactorizacionPlus/Pasadita#77]
El administrador debe poder modificar los privilegios de un Residente para poder convertirlo en un Residente Encargado.

# Requerimientos

## Backend

- Endpoint para poder modificar los privilegios de un Residente cualquiera en `/api/residents/role` con un método POST.
  - Debe recibir un JSON con el identificador del Residente y el Rol que se desea asignar (`NORMAL`, `SUPER`).

## Frontend

- Formulario dentro de los Residentes para poder asignar a un Residente como Encargado.

**Comment by LeoCorea** [comment]
¿Todos los residentes tiene un `rol` por default?
